name: run bot.py

on:
  schedule: 
    - cron: '17,47 * * * *'
  workflow_dispatch: 
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner, updated to @v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run bot.py
        env:
          STATIC_PRIVATE_KEY: ${{ secrets.STATIC_PRIVATE_KEY }}
        run: python bot.py
          
      - name: commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          git push
